# Generated by Django 4.2.26 on 2025-12-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='name',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='courses',
            name='credit_hours',
            field=models.CharField(default='', max_length=15),
        ),
    ]
