# Generated by Django 4.2.26 on 2025-12-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_courses_name_courses_course_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='credit_hours',
            new_name='domain',
        ),
    ]
