# Generated by Django 4.2.26 on 2025-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_credit_hours_courses_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='name',
        ),
        migrations.AddField(
            model_name='subjects',
            name='credit_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
