# Generated by Django 4.2.26 on 2025-12-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_subjects_name_subjects_credit_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(default='', max_length=20),
        ),
    ]
