# Generated by Django 4.2.26 on 2025-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_option_1_question_option_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
