# Generated by Django 4.2.26 on 2025-12-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=15)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.students')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.subjects')),
            ],
        ),
    ]
