# Generated by Django 6.0 on 2025-12-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='confirmpassword',
        ),
    ]
