# Generated by Django 6.0 on 2025-12-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_students_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
