# Generated by Django 6.0 on 2025-12-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_students_email_alter_students_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
